### ISSUE TITLE
#4 アカウント作成の動作確認するもユーザーが登録できずエラーが出る。

### ISSUE THREAD

**Issue by naopandao** [yunixy-creado/tinder-mini#6]
![スクリーンショット 2022-07-13 15 46 44](https://user-images.githubusercontent.com/85982815/178669021-062e293c-46f6-4c73-8813-e45cf4627d0b.png)
![スクリーンショット 2022-07-13 15 46 54](https://user-images.githubusercontent.com/85982815/178669055-de285cc0-ad50-42ec-830a-29e1c04116ca.png)

**Comment by rinaata-aezisai** [comment]
deviseがbundle installされてなかったかも
